# Generated by Django 4.2.1 on 2023-05-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, db_index=True, verbose_name='Подзоголовок')),
                ('date', models.DateTimeField(blank=True, db_index=True, verbose_name='Дата')),
                ('image', models.ImageField(upload_to='images/% Y/% m/% d/')),
            ],
        ),
    ]
