# Generated by Django 4.2.1 on 2023-05-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=70, verbose_name='ФИО')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('review', models.TextField(blank=True, db_index=True, verbose_name='Отзыв')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('image', models.ImageField(upload_to='images/reviews/% Y/% m/% d/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
