# Generated by Django 4.2.1 on 2023-05-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='Адрес'),
        ),
    ]
